# Generated by Django 4.1 on 2022-08-15 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0002_age_category_model_subcategory_model_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product_model',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Admin_App.category_model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_model',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
