# Generated by Django 4.1 on 2022-08-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0003_product_model_available_product_model_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='offer_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
