# Generated by Django 4.1 on 2022-08-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0004_product_model_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory_model',
            name='image',
        ),
        migrations.AddField(
            model_name='product_model',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Choose your Gender', max_length=20),
        ),
    ]
