# Generated by Django 4.1 on 2022-08-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileregister_model',
            name='user_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
