# Generated by Django 4.1 on 2022-08-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts_App', '0002_profileregister_model_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileregister_model',
            name='dp',
            field=models.ImageField(blank=True, upload_to='users/profile_pics'),
        ),
    ]
