# Generated by Django 4.1 on 2022-08-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts_App', '0003_profileregister_model_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileregister_model',
            name='dp',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
