# Generated by Django 4.1 on 2022-08-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts_App', '0005_alter_profileregister_model_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileregister_model',
            name='mobile_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profileregister_model',
            name='dp',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
