# Generated by Django 4.1 on 2022-08-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts_App', '0007_profileregister_model_banner_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileregister_model',
            name='banner_pic',
        ),
    ]
